!
!  SourceFile1.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  9/20/2019 2:10:36 PM
!
program change_C_to_F
implicit none
integer :: C=5 
real :: F
 F=(9.0/5.0)*C+32.0
print*,'F=',F
end program change_C_to_F
