!
!  SourceFile1.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  9/20/2019 2:53:47 PM
!
program cal_round_area
real :: A=2.0, B=2.0, C=1.0, S
	S=(A+B+C)/2.0
print*, '삼각형의 둘레 :',A+B+C
print*, '삼각형의 면적 :',(S*(S-A)*(S-B)*(S-C))**(1/2.0) 
end program cal_round_area