!
!  ex3.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  9/27/2019 3:38:03 PM
!
program ex3




real ::a,b,c,d,e,f
print*,"기울기 계산에 사용할 6개의 수를 쉼표를 사용하여 입력하시오."
read*, a,b,c,d,e,f 
if ((-a/b)/=(-d/e)) then
print*,"교차한다."
else if ((-a/b)==(-d/e)) then
print*,"평행한다."
else if ((-a/b)*(-d/e)==-1) then
print*,"직교한다."
end if  

end program ex3