!
!  ex2.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  9/27/2019 2:47:15 PM
!

program ex2
integer ::YYYY, MM, DD, yyyymmdd
print*, "날짜를 YYYYMMDD 형태로 입력하시오."
read*, YYYYMMDD

! 20160727/10000


yyyy= YYYYMMDD/10000

mm= (YYYYMMDD-yyyy*10000)/100

dd=yyyymmdd-(yyyy*10000+mm*100)
print*,YYYYMMDD/10000,"년",(YYYYMMDD-yyyy*10000)/100,"월",YYYYMMDD-(yyyy*10000+mm*100),"일"


end program ex2
