!
!  SourceFile1.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  10/11/2019 11:43:48 AM
!

program ex_1
implicit none
integer :: i
 do i=0,999
  if (mod(i,10)==0) then
   print*, i
  end if
 enddo
end program ex_1
