!
!  SourceFile2.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  10/11/2019 11:52:19 AM
!

program ex_2
implicit none
integer :: i,N
print*, "정수 N을 입력하시오."
read*, N
do i=1,1000
  if (mod(i,N)==0) then
   print*, i
  end if   
 enddo 
end program ex_2