!
!  ex_1.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  10/18/2019 11:04:49 AM
!

program ex_1
implicit none
integer ::i=0, subtract=0
do while (subtract<50)
 i=i+1
 subtract=(i+1)**2-i**2
print*,subtract
enddo 
end program ex_1

