!
!  ex_2.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  10/18/2019 11:42:21 AM
!

program ex_2
implicit none
integer ::i=0,sum1=0,sum2=1,sum3,n
print*,"양의 정수 N을 입력하시오."
read*, n
do
 sum3=sum1+sum2
 sum1=sum2
 sum2=sum3
 i=i+1
 write(*,'(i,$)')sum1
 if(i.eq.n) exit
enddo
end program ex_2