!
!  ex_2.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  11/15/2019 12:44:33 PM
!

program ex_2
implicit none
integer, dimension(1)::fibo
integer::n,i=0,sum1=0,sum2=1,sum3
read*,n
do 
 if(i==n-1)exit
 i=i+1
 sum3=sum1+sum2
 sum1=sum2
 sum2=sum3
 write(*,'(i,$)')sum1
end do
fibo=(/sum3/)
print*,fibo
end program ex_2