!
!  ex1.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  11/15/2019 11:04:27 AM
!
program ex_1
implicit none
integer::n=0,i=0
real::appro,sum=0,mea=0,fact
real, dimension(2)::a
do n=0,10
 do i=0,n
  if(i==0)then
   fact=1
  else
   fact=fact*i 
  end if
 end do
appro=(3**n)/fact
sum=sum+appro
mea=((exp(3.0)-sum)/exp(3.0))*100
a=(/sum,mea/)
print*,"n=",n, a
end do
end program ex_1