!
!  ex_3.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  11/15/2019 1:11:42 PM
!

program ex_3
implicit none
integer::date,year,month,day,julian_day,i
integer, dimension(12)::jul
 jul=(/31,28,31,30,31,30,31,31,30,31,30,31/)
read*,date
year=date/10000
month=(date-year*10000)/100
day=date-(year*10000+month*100)
if(mod(year,4)==0.and.mod(year,100)/=0.or.mod(year,400)==0) then
 jul(2)=29
end if
do i=1,month-1
 julian_day=julian_day+jul(i)
end do
print*, julian_day+day  , date
end program ex_3