!
!  ex1.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  11/22/2019 11:21:27 AM
!

program ex_1
implicit none
integer::det_a,detc,detd,dete
real::x,y,z
integer,dimension(9)::A
integer,dimension(9)::c
integer,dimension(9)::d
integer,dimension(9)::e
A=(/2,1,1,4,-6,0,-2,7,2/)
c=(/3,1,1,10,-6,0,-5,7,2/)
d=(/2,3,1,4,10,0,-2,-5,2/)
e=(/2,1,3,4,-6,10,-2,7,-5/)
det_a=A(1)*(A(5)*A(9)-A(6)*A(8))-A(2)*(A(4)*A(9)-A(6)*A(9))+A(3)*(A(4)*A(8)-A(5)*A(7))
detc=c(1)*(c(5)*c(9)-c(6)*c(8))-c(2)*(c(4)*c(9)-c(6)*c(7))+c(3)*(c(4)*c(8)-c(5)*c(7))
detd=d(1)*(d(5)*d(9)-d(6)*d(8))-d(2)*(d(4)*d(9)-d(6)*d(7))+d(3)*(d(4)*d(8)-d(5)*d(7))
dete=e(1)*(e(5)*e(9)-e(6)*e(8))-e(2)*(e(4)*e(9)-e(6)*e(7))+e(3)*(e(4)*e(8)-e(5)*e(7))
x=detc/det_a
y=detd/det_a
z=dete/det_a
if (det_a/=0) then
 print*,"x= ",x
 print*,"y= ",y
 print*,"z= ",z
else
end if
end program ex_1